name: PR Check

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pr-check:
    uses: huseyinbabal/rust-actions/.github/workflows/pr-check.yml@main
    with:
      run_tests: true
      run_fmt: true
      run_clippy: true
      check_coverage: true
      coverage_threshold: 60
